# Generated by Django 3.1.4 on 2022-03-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_account', '0002_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='developer',
            name='bio',
            field=models.TextField(max_length=750),
        ),
    ]
