# Generated by Django 3.1.4 on 2022-03-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci_account', '0003_auto_20220330_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
