# Form implementation generated from reading ui file 'c:\Users\Marin\Documents\Team-Project_Python\backend_files\ui_files\deleteData.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(500, 200)
        self.widget = QtWidgets.QWidget(login_window)
        self.widget.setGeometry(QtCore.QRect(0, 0, 500, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color:#16191d;")
        self.widget.setObjectName("widget")
        self.label_product = QtWidgets.QLabel(self.widget)
        self.label_product.setGeometry(QtCore.QRect(70, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_product.setFont(font)
        self.label_product.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_product.setObjectName("label_product")
        self.lineEdit_product = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_product.setGeometry(QtCore.QRect(200, 40, 211, 31))
        self.lineEdit_product.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_product.setObjectName("lineEdit_product")
        self.pushButton_commit = QtWidgets.QPushButton(self.widget)
        self.pushButton_commit.setGeometry(QtCore.QRect(60, 130, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        self.pushButton_commit.setFont(font)
        self.pushButton_commit.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"border-radius: 20px;")
        self.pushButton_commit.setObjectName("pushButton_commit")
        self.label_result = QtWidgets.QLabel(self.widget)
        self.label_result.setGeometry(QtCore.QRect(90, 80, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "Dialog"))
        self.label_product.setText(_translate("login_window", "Product ID:"))
        self.pushButton_commit.setText(_translate("login_window", "Delete Data"))
