# Form implementation generated from reading ui file 'c:\Users\Marin\Documents\Team-Project_Python\login.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(1200, 800)
        self.widget = QtWidgets.QWidget(login_window)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.636, x2:0, y2:0.999591, stop:0 rgba(0, 0, 127, 255), stop:0.99435 rgba(0, 0, 0, 255));}")
        self.widget.setObjectName("widget")
        self.label_login = QtWidgets.QLabel(self.widget)
        self.label_login.setEnabled(True)
        self.label_login.setGeometry(QtCore.QRect(520, 120, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("color:white;\n"
"font: 900 36pt \"Arial Black\";")
        self.label_login.setObjectName("label_login")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(410, 200, 421, 41))
        self.label_2.setStyleSheet("color:white;\n"
"font: 900 16pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_login = QtWidgets.QPushButton(self.widget)
        self.pushButton_login.setGeometry(QtCore.QRect(430, 450, 331, 61))
        self.pushButton_login.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 900 14pt \"Arial Black\";")
        self.pushButton_login.setObjectName("pushButton_login")
        self.lineEdit_username = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_username.setGeometry(QtCore.QRect(420, 290, 351, 41))
        self.lineEdit_username.setStyleSheet("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_password.setGeometry(QtCore.QRect(420, 360, 351, 41))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_username = QtWidgets.QLabel(self.widget)
        self.label_username.setGeometry(QtCore.QRect(420, 260, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        self.label_username.setFont(font)
        self.label_username.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.widget)
        self.label_password.setGeometry(QtCore.QRect(420, 340, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        self.label_password.setFont(font)
        self.label_password.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_password.setObjectName("label_password")
        self.label_result = QtWidgets.QLabel(self.widget)
        self.label_result.setGeometry(QtCore.QRect(420, 410, 341, 21))
        self.label_result.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 900 12pt \"Arial Black\";")
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "Dialog"))
        self.label_login.setText(_translate("login_window", "Login"))
        self.label_2.setText(_translate("login_window", "Sign in to your existing account"))
        self.pushButton_login.setText(_translate("login_window", "Login"))
        self.label_username.setText(_translate("login_window", "Username:"))
        self.label_password.setText(_translate("login_window", "Password: "))
