# Form implementation generated from reading ui file 'c:\Users\Marin\Documents\Team-Project_Python\userLogin.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(1200, 800)
        self.widget = QtWidgets.QWidget(login_window)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.636, x2:0, y2:0.999591, stop:0 rgba(0, 0, 127, 255), stop:0.99435 rgba(0, 0, 0, 255));}")
        self.widget.setObjectName("widget")
        self.label_login = QtWidgets.QLabel(self.widget)
        self.label_login.setEnabled(True)
        self.label_login.setGeometry(QtCore.QRect(270, 130, 661, 121))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("color:white;\n"
"font: 900 36pt \"Arial Black\";")
        self.label_login.setObjectName("label_login")
        self.pushButton_employee = QtWidgets.QPushButton(self.widget)
        self.pushButton_employee.setGeometry(QtCore.QRect(180, 310, 361, 191))
        self.pushButton_employee.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 900 14pt \"Arial Black\";")
        self.pushButton_employee.setObjectName("pushButton_employee")
        self.pushButton_customer = QtWidgets.QPushButton(self.widget)
        self.pushButton_customer.setGeometry(QtCore.QRect(620, 310, 361, 191))
        self.pushButton_customer.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 900 14pt \"Arial Black\";")
        self.pushButton_customer.setObjectName("pushButton_customer")

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "Dialog"))
        self.label_login.setText(_translate("login_window", "CHOOSE WHO YOU ARE"))
        self.pushButton_employee.setText(_translate("login_window", "EMPLOYEE"))
        self.pushButton_customer.setText(_translate("login_window", "CUSTOMER"))
