# Form implementation generated from reading ui file 'c:\Users\Marin\Documents\Team-Project_Python\Back-end Files\welcome.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(1200, 800)
        self.widget = QtWidgets.QWidget(login_window)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.636, x2:0, y2:0.999591, stop:0 rgba(0, 0, 127, 255), stop:0.99435 rgba(0, 0, 0, 255));}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(420, 130, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
"font: 900 36pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(360, 210, 421, 41))
        self.label_2.setStyleSheet("color:white;\n"
"font: 900 16pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_login = QtWidgets.QPushButton(self.widget)
        self.pushButton_login.setGeometry(QtCore.QRect(370, 300, 331, 61))
        self.pushButton_login.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 900 14pt \"Arial Black\";")
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_newAcc = QtWidgets.QPushButton(self.widget)
        self.pushButton_newAcc.setGeometry(QtCore.QRect(370, 390, 331, 61))
        self.pushButton_newAcc.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 900 14pt \"Arial Black\";")
        self.pushButton_newAcc.setObjectName("pushButton_newAcc")

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "Dialog"))
        self.label.setText(_translate("login_window", "Welcome"))
        self.label_2.setText(_translate("login_window", "Sign in or create a new account"))
        self.pushButton_login.setText(_translate("login_window", "Login"))
        self.pushButton_newAcc.setText(_translate("login_window", "Create a new account"))
