# Generated by Django 3.1.4 on 2022-03-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
