# Generated by Django 4.0.3 on 2022-03-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=126)),
                ('last_name', models.CharField(max_length=126)),
            ],
        ),
    ]
