# Generated by Django 4.0.3 on 2022-03-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=126)),
                ('last_name', models.CharField(max_length=126)),
                ('story', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
