# Generated by Django 4.0.3 on 2022-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_app', '0002_teammembers_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='story',
            field=models.TextField(max_length=1000),
        ),
    ]
