# Generated by Django 4.0.3 on 2022-03-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci_app', '0003_alter_teammembers_story'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
    ]
