# Generated by Django 4.0.3 on 2022-03-08 22:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_app', '0004_rename_teammembers_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/images/'), upload_to=''),
        ),
    ]
