# Generated by Django 4.0.3 on 2022-03-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci_app', '0006_alter_teammember_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='photo',
        ),
    ]
