# Generated by Django 4.0.3 on 2022-03-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_app', '0007_remove_teammember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_images'),
        ),
    ]
