# Generated by Django 4.0.3 on 2022-03-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_app', '0008_teammember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
