# Generated by Django 4.0.3 on 2022-03-10 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ci_app', '0015_rename_inventory_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ci_app.product'),
        ),
    ]
