# Generated by Django 4.0.3 on 2022-03-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_app', '0016_alter_customerorder_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_cost',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
