# Generated by Django 4.0.3 on 2022-03-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_app', '0017_alter_product_sale_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorder',
            old_name='date',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='customerorderitem',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='cust_email',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='cust_location',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='cust_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='cust_location',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
