# Generated by Django 4.0.3 on 2022-04-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorders',
            name='order_id',
        ),
    ]
