# Generated by Django 4.0.3 on 2022-04-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_order', '0003_payment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
    ]
