# Generated by Django 4.0.3 on 2022-04-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci_order', '0003_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='email',
        ),
    ]
