# Generated by Django 3.1.4 on 2022-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_photo',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
