# Generated by Django 4.0.3 on 2022-04-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_category', '0002_auto_20220329_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
